services:
  loki:
    image: 'grafana/loki:3.5.5'
    container_name: 'loki'
    command: '--config.file=/etc/loki/config.yaml'
    volumes:
      - 'loki-data:/loki'
      - './loki/config.yaml:/etc/loki/config.yaml:ro'
    restart: 'unless-stopped'
    healthcheck:
      test:
        - 'CMD'
        - 'wget'
        - '--spider'
        - '-q'
        - 'http://localhost:3100/ready'
      interval: 30s
      timeout: 10s
      retries: 3

  alloy:
    image: 'grafana/alloy:latest'
    container_name: 'alloy'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy/config.yaml:/etc/alloy/config.yaml:ro
    command:
      - run
      - /etc/alloy/config.alloy

volumes:
  loki-data: